{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "225a99c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 113\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.datasets import cifar10\n",
    "from tensorflow.keras.models import Model,Sequential\n",
    "from tensorflow.keras.layers import Activation,Input,BatchNormalization,Flatten, Dense, Conv2D, MaxPool2D,AveragePooling2D,Dropout\n",
    "from tensorflow.keras.losses import SparseCategoricalCrossentropy\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.callbacks import EarlyStopping"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "76450b7a",
   "metadata": {},
   "outputs": [],
   "source": [
    "class BottleNeck():\n",
    "\n",
    "    def __init__(self, num_filters, stride):\n",
    "\n",
    "        self.conv1 = Conv2D(filters = num_filters, kernel_size=(1,1), strides= (1,1), padding = 'same')\n",
    "\n",
    "        self.bn1 = BatchNormalization()\n",
    "\n",
    "        \n",
    "\n",
    "        self.conv2 = Conv2D(filters = num_filters, kernel_size=(3,3), strides= stride, padding = 'same')\n",
    "\n",
    "        self.bn2 = BatchNormalization()\n",
    "        \n",
    "\n",
    "        self.shortcut = Sequential()\n",
    "\n",
    "        self.shortcut.add(Conv2D(num_filters, kernel_size=(1,1), strides= stride, padding = 'same'))\n",
    "\n",
    "        self.shortcut.add(BatchNormalization())\n",
    "\n",
    "            \n",
    "\n",
    "    def call(self, inputs, training=None, **kwargs):\n",
    "\n",
    "        \n",
    "\n",
    "        x = self.conv1(inputs)\n",
    "\n",
    "        x = tf.nn.relu(self.bn1(x))\n",
    "\n",
    "        x = self.conv2(x)\n",
    "\n",
    "        x = tf.nn.relu(self.bn2(x))\n",
    "\n",
    "        output = tf.nn.relu(tf.keras.layers.add([self.shortcut(inputs), x]))\n",
    "\n",
    "        \n",
    "\n",
    "        return output\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7d477c7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def _make_layer(num_filters, num_blocks, stride):\n",
    "\n",
    "    \n",
    "\n",
    "    res_block = Sequential()\n",
    "\n",
    "    res_block.add(BottleNeck(num_filters, stride=stride))\n",
    "\n",
    "    \n",
    "\n",
    "    for _ in range(1, num_blocks): # 1에서 시작해서 num_block 수만큼 반복\n",
    "\n",
    "        res_block.add(BottleNeck(num_filters, stride=1))\n",
    "\n",
    "    \n",
    "\n",
    "    return res_block\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5b3030de",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ResNet():\n",
    "\n",
    "    def __init__(self, num_block, num_units=10):\n",
    "\n",
    "        \n",
    "\n",
    "        self.conv1 = Conv2D(filters=64,kernel_size=(7,7),strides=(2,2),padding='same')\n",
    "\n",
    "        self.bn1 = BatchNormalization()\n",
    "\n",
    "        \n",
    "\n",
    "        self.mp1 = MaxPool2D(pool_size = (3,3), strides=(2,2), padding='same')\n",
    "\n",
    "        self.bn2 = BatchNormalization()\n",
    "\n",
    "\n",
    "        self.bt1 = _make_layer(64, num_block[0], 1)\n",
    "\n",
    "        self.bt2 = _make_layer(128, num_block[1], 2)\n",
    "\n",
    "        self.bt3 = _make_layer(256, num_block[2], 2)\n",
    "\n",
    "        self.bt4 = _make_layer(512, num_block[3], 2)\n",
    "\n",
    "        \n",
    "\n",
    "        self.av1 = AveragePooling2D(pool_size = (1,1), strides=(1,1))\n",
    "\n",
    "        self.flatten = Flatten()\n",
    "\n",
    "        self.ds1 = Dense(units=2048,activation='relu')\n",
    "\n",
    "        self.ds2 = Dense(units=1000,activation='relu')\n",
    "\n",
    "        self.ds3 = Dense(units=num_units,activation='softmax')\n",
    "\n",
    "        \n",
    "\n",
    "    def call(self, inputs, training=None, mask=None):\n",
    "\n",
    "        x = self.conv1(inputs)\n",
    "\n",
    "        x = self.bn1(x, training=training)\n",
    "\n",
    "        x = tf.nn.relu(x)\n",
    "\n",
    "        x = self.mp1(x)\n",
    "\n",
    "        x = self.bn2(x)\n",
    "\n",
    "        x = self.bt1(x, training=training)\n",
    "\n",
    "        x = self.bt2(x, training=training)\n",
    "\n",
    "        x = self.bt3(x, training=training)\n",
    "\n",
    "        x = self.bt4(x, training=training)\n",
    "\n",
    "        x = self.av1(x)\n",
    "\n",
    "        x = self.flatten(x)\n",
    "\n",
    "        x = self.ds1(x)\n",
    "\n",
    "        x = self.ds2(x)\n",
    "\n",
    "        output = self.ds3(x)\n",
    "\n",
    "\n",
    "        return output\n",
    "\n",
    "\n",
    "def ResNet34():\n",
    "\n",
    "    return ResNet(num_block = [2,2,2,2])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e5c9a93",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 12, in <module>\n",
      "    model = get_model()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 3, in get_model\n",
      "    model = ResNet34()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 76, in ResNet34\n",
      "    return ResNet(num_block = [2,2,2,2])\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 18, in __init__\n",
      "    self.bt1 = _make_layer(64, num_block[0], 1)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\2299595829.py\", line 7, in _make_layer\n",
      "    res_block.add(BottleNeck(num_filters, stride=stride))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\training\\tracking\\base.py\", line 457, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\sequential.py\", line 161, in add\n",
      "    'Found: ' + str(layer))\n",
      "TypeError: The added layer must be an instance of class Layer. Found: <__main__.BottleNeck object at 0x0000019F5A7A2F08>\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 115\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 12, in <module>\n",
      "    model = get_model()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 3, in get_model\n",
      "    model = ResNet34()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 76, in ResNet34\n",
      "    return ResNet(num_block = [2,2,2,2])\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 18, in __init__\n",
      "    self.bt1 = _make_layer(64, num_block[0], 1)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\2299595829.py\", line 7, in _make_layer\n",
      "    res_block.add(BottleNeck(num_filters, stride=stride))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\training\\tracking\\base.py\", line 457, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\sequential.py\", line 161, in add\n",
      "    'Found: ' + str(layer))\n",
      "TypeError: The added layer must be an instance of class Layer. Found: <__main__.BottleNeck object at 0x0000019F5A7A2F08>\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 12, in <module>\n",
      "    model = get_model()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\807357572.py\", line 3, in get_model\n",
      "    model = ResNet34()\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 76, in ResNet34\n",
      "    return ResNet(num_block = [2,2,2,2])\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\999697629.py\", line 18, in __init__\n",
      "    self.bt1 = _make_layer(64, num_block[0], 1)\n",
      "  File \"C:\\Users\\tlsdu\\AppData\\Local\\Temp\\ipykernel_9180\\2299595829.py\", line 7, in _make_layer\n",
      "    res_block.add(BottleNeck(num_filters, stride=stride))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\training\\tracking\\base.py\", line 457, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\sequential.py\", line 161, in add\n",
      "    'Found: ' + str(layer))\n",
      "TypeError: The added layer must be an instance of class Layer. Found: <__main__.BottleNeck object at 0x0000019F5A7A2F08>\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3396, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\tlsdu\\anaconda3\\envs\\tfgpu\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "def get_model():\n",
    "\n",
    "    model = ResNet34()\n",
    "\n",
    "    model.build(input_shape=(None,32,32,3))\n",
    "\n",
    "    model.summary()\n",
    "\n",
    "    return model\n",
    "\n",
    "\n",
    "model = get_model()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dbdce6b4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "[2.1]",
   "language": "python",
   "name": "tfgpu2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
